# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: be-config
  namespace: backend-ns
data:
  MYSQL_HOST: db-svc.database-ns.svc.cluster.local
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: myapp

