# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: "db-svc"
  namespace: database-ns
spec:
  selector:
    app: db
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306   #req send to db containerport
   